# Generated by Django 2.2.9 on 2020-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0002_questionexperiment_correct_answer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionexperiment',
            name='correct_answer_number',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
