# Generated by Django 2.2.9 on 2020-02-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0006_remove_results_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fragebogen.Question'),
        ),
        migrations.AlterField(
            model_name='results',
            name='error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fragebogen.Error'),
        ),
    ]
