# Generated by Django 2.2.9 on 2020-02-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fragebogen', '0008_auto_20200222_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='nudge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fragebogen.Nudge'),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='presentation_type',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
